### ISSUE TITLE
Should we have AS1 docs?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitystreams-test-documents#3]
https://as2.rocks/validate?url=https%3A%2F%2Frawgit.com%2Fgobengo%2Factivity-mocks%2Fmaster%2Fmocks%2Fspec%2Fextended.json

That example and the rest of the documents in [this dir of gobengo/activity-mocks](https://github.com/gobengo/activity-mocks/tree/master/mocks) are all AS1.

The as2-core document has a non-normative section on interpreting AS1 docs, but I'm not sure if that means that these are 'valid' as2.

**Comment by akuckartz** [comment]
Yes, they either are valid AS2 or they are not.

**Comment by gobengo** [comment]
http://socialwg.indiewebcamp.com/irc/social/2016-02-23#t1456251667699
